#默认端口
server:
  port: 8080

#设置数据源信息
#设置数据源信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/view


#注册映射文件
mybatis-plus:
  mapper-locations: classpath*:com/jxd/comment/mapper/impl/*.xml
  type-aliases-package: com.jxd.comment.model #设置实体类的别名

